version: "3"
services:
  mongodb:
    image: mongo
    networks:
      - let-s-publish-network
  # client:
  #   container_name: client
  #   build: ./client/
  #   volumes:
  #     - './client:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 80:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  post_api:
    build: ./services/post/
    ports:
      - "8080:8080"
    volumes:
      - ./services/post/:/post_api
      - /post_api/node_modules
    depends_on:
      - mongodb
    networks:
      - let-s-publish-network
  comment_api:
    build: ./services/comment/
    ports:
      - "8081:8081"
    volumes:
      - ./services/comment/:/comment_api
      - /comment_api/node_module
    depends_on:
      - mongodb
    networks:
      - let-s-publish-network
  profile_api:
    build: ./services/profile/
    ports:
      - "8082:8082"
    volumes:
      - ./services/profile:/profile_api
      - /profile_api/node_modules
    depends_on:
      - mongodb
    networks:
      - let-s-publish-network
  notification_api:
    build: ./services/notification/
    ports:
      - "8083:8083"
    volumes:
      - ./services/notification/:/notification_api
      - /notification_api/node_modules
    depends_on:
      - mongodb
    networks:
      - let-s-publish-network
networks:
  let-s-publish-network:
    driver: bridge